// <auto-generated />
using System;
using Inventory.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Domain.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250503101251_qqk")]
    partial class qqk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.Entites.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74e7a19d-fc43-4010-b346-637490001867",
                            Email = "admin@inventory.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@INVENTORY.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMiZmNAI2ln7b8SJvJDbze1J/6XmW+UtcolWxjlshQt4IPtuPhnMyPAKzLjWcqIQOg==",
                            PhoneNumber = "+1-555-123-4567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4746add6-5251-4011-8dbe-d4ddb47cce54",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbb439e7-2592-4cd9-b78c-9d5b86e5fcaa",
                            Email = "manager@inventory.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@INVENTORY.COM",
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAECzZIgrKY3FEMIp/pYUIWd+1yt5kUJ7PAzP8mI2DiUHAk25chOhFwYJcrtC9jnXxSg==",
                            PhoneNumber = "+1-555-234-5678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "72dec0c7-6c9c-4bc4-805c-35cbdfbbea37",
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b8a235d7-51e4-43b8-8da7-66f8d853f6c1",
                            Email = "user@inventory.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@INVENTORY.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEL/YOZz2bw+wnZCXDuZxQx50ZRbgNBnh/AFNilrBE1UvZJCc1flOOefgDh9hfSVmMw==",
                            PhoneNumber = "+1-555-345-6789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc3f8f5c-d1d9-4987-9c27-fc7ad0ce7058",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 3, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9169),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 4, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9176),
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 5, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9178),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 6, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9179),
                            Name = "Food & Beverages"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 7, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9180),
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinationWarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceWarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceWarehouseId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 3, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(848),
                            ProductId = 1,
                            Quantity = 10,
                            SourceWarehouseId = 1,
                            TransactionType = 0,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 8, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(851),
                            ProductId = 2,
                            Quantity = 5,
                            SourceWarehouseId = 1,
                            TransactionType = 0,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(858),
                            ProductId = 2,
                            Quantity = 2,
                            SourceWarehouseId = 1,
                            TransactionType = 1,
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 19, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(860),
                            DestinationWarehouseId = 2,
                            ProductId = 1,
                            Quantity = 5,
                            SourceWarehouseId = 1,
                            TransactionType = 2,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 13, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(862),
                            ProductId = 3,
                            Quantity = 25,
                            SourceWarehouseId = 1,
                            TransactionType = 0,
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 1, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(751),
                            IsRead = false,
                            Message = "Product Vacuum Cleaner has reached a low stock level (3 remaining). Minimum threshold is 5.",
                            ProductId = 2,
                            Title = "Low Stock Alert",
                            Type = 0,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 1, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(764),
                            IsRead = false,
                            Message = "Product Vacuum Cleaner has reached a low stock level (3 remaining). Minimum threshold is 5.",
                            ProductId = 2,
                            Title = "Low Stock Alert",
                            Type = 0,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 2, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(765),
                            IsRead = false,
                            Message = "Product Cooking Oil has reached a low stock level (7 remaining). Minimum threshold is 10.",
                            ProductId = 5,
                            Title = "Low Stock Alert",
                            Type = 0,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 2, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(767),
                            IsRead = true,
                            Message = "Product Cooking Oil has reached a low stock level (7 remaining). Minimum threshold is 10.",
                            ProductId = 5,
                            Title = "Low Stock Alert",
                            Type = 0,
                            UserId = "2"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(768),
                            IsRead = false,
                            Message = "Price of product Laptop has changed to $1200.",
                            ProductId = 1,
                            Title = "Product Information",
                            Type = 2,
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 18, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9308),
                            Description = "High-performance laptop with 16GB RAM",
                            LowStockThreshold = 5,
                            Name = "Laptop",
                            Price = 1200m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 23, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9310),
                            Description = "2000W powerful vacuum cleaner",
                            LowStockThreshold = 5,
                            Name = "Vacuum Cleaner",
                            Price = 180m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 13, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9312),
                            Description = "Latest model with 5G capability",
                            LowStockThreshold = 8,
                            Name = "Smartphone",
                            Price = 899m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 4, 8, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9313),
                            Description = "Ergonomic design for comfort",
                            LowStockThreshold = 4,
                            Name = "Office Chair",
                            Price = 250m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9317),
                            Description = "1 liter vegetable cooking oil",
                            LowStockThreshold = 10,
                            Name = "Cooking Oil",
                            Price = 7.99m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 4, 15, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9319),
                            Description = "Men's formal shirt, 100% cotton",
                            LowStockThreshold = 10,
                            Name = "Dress Shirt",
                            Price = 45.50m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 4, 11, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9320),
                            Description = "Noise-cancelling wireless headphones",
                            LowStockThreshold = 5,
                            Name = "Headphones",
                            Price = 199.99m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 4, 21, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9322),
                            Description = "Automatic drip coffee maker with timer",
                            LowStockThreshold = 4,
                            Name = "Coffee Maker",
                            Price = 89.95m,
                            Quantity = 9
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.ProductWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductWarehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 19, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9347),
                            ProductId = 1,
                            Quantity = 10,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 24, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9348),
                            ProductId = 2,
                            Quantity = 2,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 14, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9350),
                            ProductId = 3,
                            Quantity = 15,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 9, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9351),
                            ProductId = 4,
                            Quantity = 8,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 29, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9352),
                            ProductId = 5,
                            Quantity = 5,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 4, 16, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9353),
                            ProductId = 6,
                            Quantity = 20,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 4, 12, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9354),
                            ProductId = 7,
                            Quantity = 12,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 4, 22, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9355),
                            ProductId = 8,
                            Quantity = 6,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 4, 19, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9356),
                            ProductId = 1,
                            Quantity = 5,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 4, 14, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9357),
                            ProductId = 3,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 4, 16, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9358),
                            ProductId = 6,
                            Quantity = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 4, 12, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9359),
                            ProductId = 7,
                            Quantity = 6,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 4, 24, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9361),
                            ProductId = 2,
                            Quantity = 1,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 4, 9, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9362),
                            ProductId = 4,
                            Quantity = 4,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 4, 29, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9363),
                            ProductId = 5,
                            Quantity = 2,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 4, 22, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9364),
                            ProductId = 8,
                            Quantity = 3,
                            WarehouseId = 3
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(924),
                            DataJson = "[]",
                            Description = "Report showing products that have reached low stock levels",
                            GeneratedAt = new DateTime(2025, 4, 28, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(921),
                            GeneratedByUserId = "1",
                            Title = "Low Stock Products Report",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 2, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1180),
                            DataJson = "[]",
                            Description = "Report showing inventory transactions from the past 30 days",
                            EndDate = new DateTime(2025, 5, 3, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1172),
                            GeneratedAt = new DateTime(2025, 5, 2, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1172),
                            GeneratedByUserId = "1",
                            StartDate = new DateTime(2025, 4, 3, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1168),
                            Title = "Transaction History (2025-04-03 - 2025-05-03)",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 3, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1187),
                            DataJson = "[]",
                            Description = "Report showing current inventory status",
                            GeneratedAt = new DateTime(2025, 5, 3, 10, 12, 51, 107, DateTimeKind.Utc).AddTicks(1186),
                            GeneratedByUserId = "2",
                            Title = "Inventory Summary 2025-05-03",
                            Type = 2
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 4, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9283),
                            Location = "New York",
                            Name = "Main Warehouse"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 14, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9285),
                            Location = "Los Angeles",
                            Name = "West Coast Hub"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 24, 10, 12, 50, 931, DateTimeKind.Utc).AddTicks(9286),
                            Location = "Chicago",
                            Name = "Midwest Center"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "a5c6625d-ac32-4739-b922-659d74ffcf5a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "db4b01f2-e61d-43de-9119-cb32a400cbb3",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "7a6bb340-a3ff-45c9-838c-492dd83e20cb",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entites.InventoryTransaction", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.Warehouse", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId");

                    b.HasOne("Inventory.Domain.Entites.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entites.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId");

                    b.HasOne("Inventory.Domain.Entites.Warehouse", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId");

                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("Product");

                    b.Navigation("Report");

                    b.Navigation("SourceWarehouse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Notification", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.Product", "Product")
                        .WithMany("Notifications")
                        .HasForeignKey("ProductId");

                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Product", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.ProductWarehouse", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", null)
                        .WithMany("ProductWarehouse")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Inventory.Domain.Entites.Product", "Product")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entites.Warehouse", "Warehouse")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Report", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", "GeneratedByUser")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Inventory.Domain.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Domain.Entites.ApplicationUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ProductWarehouse");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Product", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("ProductWarehouses");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Inventory.Domain.Entites.Warehouse", b =>
                {
                    b.Navigation("ProductWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
